In [1]:
import pandas as pd
import numpy as np

In [23]:
df = pd.read_pickle("../data/preprocess_train_dimbat_label_2013.pkl")
df.head(5)

id                                               text  \
0  406553907700449280  terrible here in glasgow helicopter crashed in...   
1  406555220513394688  helicopter 'crashes into pub in glasgow' <URL>...   
2  406555392492462080  breaking: a helicopter has crashed in to the r...   
3  406555799344136193  labour mp jim murphy says a helicopter has cra...   
4  406556302643822592  anybody heard anything about a helicopter cras...   

   relevance                                         text_clean  \
0          8  terrible here in glasgow helicopter crashed in...   
1          8  helicopter 'crashes into pub in glasgow'  the ...   
2          8  breaking: a helicopter has crashed in to the r...   
3          8  labour mp jim murphy says a helicopter has cra...   
4          8  anybody heard anything about a helicopter cras...   

                                              lemmas  \
0  [terrible, glasgow, helicopter, crash, roof, pub]   
1     [helicopter, crash, pub, glasgow, clutha, bar]   
2  [breaking, helicopter, crash, roof, glasgow, c...   
3  [labour, mp, jim, murphy, helicopter, crash, r...   
4   [anybody, hear, helicopter, crash, pub, glasgow]   

                                          text_lemma  
0                    terrible glasgow crash roof pub  
1                       crash pub glasgow clutha bar  
2  breaking crash roof glasgow city centre pub fo...  
3                             crash roof pub glasgow  
4                     anybody hear crash pub glasgow

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 35313 entries, 0 to 68952
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   id          35313 non-null  object
 1   text        35313 non-null  object
 2   relevance   35313 non-null  int64 
 3   text_clean  35313 non-null  object
 4   lemmas      35313 non-null  object
 5   text_lemma  35313 non-null  object
dtypes: int64(1), object(5)
memory usage: 1.9+ MB


In [2]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification, pipeline
from sklearn.metrics import confusion_matrix, classification_report

In [26]:
tweets = list(df["text_clean"])

In [ ]:
#tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
#tf_model = TFAutoModelForSequenceClassification.from_pretrained("../models/dimbat_disaster_type_distilbert_model")

In [3]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("sacculifer/dimbat_disaster_type_distilbert")

tf_model = TFAutoModelForSequenceClassification.from_pretrained("sacculifer/dimbat_disaster_type_distilbert")

Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB



2022-08-06 22:26:03.998812: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-08-06 22:26:03.999047: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
Some layers from the model checkpoint at sacculifer/dimbat_disaster_type_distilbert were not used when initializing TFDistilBertForSequenceClassification: ['dropout_39']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertFo

In [4]:
classifier = pipeline("text-classification", tokenizer=tokenizer, model=tf_model)

In [29]:
output = classifier(tweets)

In [9]:
output

[{'label': 'LABEL_4', 'score': 0.9893994927406311},
 {'label': 'LABEL_4', 'score': 0.9882578253746033},
 {'label': 'LABEL_4', 'score': 0.9891908168792725},
 {'label': 'LABEL_4', 'score': 0.9897446036338806},
 {'label': 'LABEL_4', 'score': 0.9891011118888855},
 {'label': 'LABEL_4', 'score': 0.9892734885215759},
 {'label': 'LABEL_4', 'score': 0.9885880947113037},
 {'label': 'LABEL_4', 'score': 0.9882180094718933},
 {'label': 'LABEL_4', 'score': 0.9876585602760315},
 {'label': 'LABEL_8', 'score': 0.43943557143211365},
 {'label': 'LABEL_4', 'score': 0.6056935787200928},
 {'label': 'LABEL_4', 'score': 0.9889737367630005},
 {'label': 'LABEL_4', 'score': 0.9889073371887207},
 {'label': 'LABEL_4', 'score': 0.9861086010932922},
 {'label': 'LABEL_3', 'score': 0.6746788024902344},
 {'label': 'LABEL_4', 'score': 0.9888759255409241},
 {'label': 'LABEL_4', 'score': 0.9891656041145325},
 {'label': 'LABEL_4', 'score': 0.4071788489818573},
 {'label': 'LABEL_4', 'score': 0.9898881316184998},
 {'label': 

In [30]:
y_pred = [d["label"] for d in output]

In [31]:
y_score = [d["score"] for d in output]

In [32]:
df['predict'] = y_pred

In [33]:
df['predict_score'] = y_score

In [41]:
df['predict'] = df['predict'].replace('LABEL_1', 1)
df['predict'] = df['predict'].replace('LABEL_2', 2)
df['predict'] = df['predict'].replace('LABEL_3', 3)
df['predict'] = df['predict'].replace('LABEL_4', 4)
df['predict'] = df['predict'].replace('LABEL_5', 5)
df['predict'] = df['predict'].replace('LABEL_6', 6)
df['predict'] = df['predict'].replace('LABEL_7', 7)
df['predict'] = df['predict'].replace('LABEL_8', 8)
df['predict'] = df['predict'].replace('LABEL_9', 9)
df['predict'] = df['predict'].replace('LABEL_0', 10)


In [44]:
df['p_label'] = y_pred

In [45]:
df['p_label'].value_counts()

LABEL_3    9211
LABEL_7    5934
LABEL_2    5926
LABEL_6    4899
LABEL_4    4839
LABEL_8    2372
LABEL_5    1271
LABEL_9     850
LABEL_1      11
Name: p_label, dtype: int64

In [38]:
df['relevance'].value_counts()

3     9254
2     5992
7     5842
4     4800
6     4782
8     2352
5      865
9      762
10     664
Name: relevance, dtype: int64

In [42]:
df['predict'].value_counts()

3    9211
7    5934
2    5926
6    4899
4    4839
8    2372
5    1271
9     850
1      11
Name: predict, dtype: int64

In [39]:
print(confusion_matrix(df["relevance"], df["predict"]))
print(classification_report(df["relevance"], df["predict"]))

[[   0    0    0    0    0    0    0    0    0    0]
 [   2 5604   44  105   10   85  116   10   16    0]
 [   1   49 8919  173   18   37   25   18   14    0]
 [   3   66   50 4474   16  137   41    6    7    0]
 [   0    2   18    3  833    0    1    7    1    0]
 [   3   79    5   58   28 4431  173    4    1    0]
 [   1   25    9   18   13  191 5568   13    4    0]
 [   0   12    2    0    2   17    4 2313    2    0]
 [   0    1    0    0    0    0    0    1  760    0]
 [   1   88  164    8  351    1    6    0   45    0]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         0
           2       0.95      0.94      0.94      5992
           3       0.97      0.96      0.97      9254
           4       0.92      0.93      0.93      4800
           5       0.66      0.96      0.78       865
           6       0.90      0.93      0.92      4782
           7       0.94      0.95      0.95      5842
           8       0.98      0.98   

/Users/xuxu/neuefische/NLPower-capstone-project/.venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/xuxu/neuefische/NLPower-capstone-project/.venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/xuxu/neuefische/NLPower-capstone-project/.venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
 

In [ ]:
#df.to_pickle("../data/preprocess_train_dimbat_2018_type_pred.pkl")

In [ ]:
#df_new = pd.read_pickle("../data/preprocess_train_dimbat_2018_type_pred.pkl")

In [ ]:
df.sample(10)

In [5]:
text = "CDC's concern over UK's Monkeypo outbreak and more"

In [6]:
output_test = classifier(text)

In [7]:
output_test

[{'label': 'LABEL_1', 'score': 0.968468427658081}]

In [8]:
output_test[0]["label"]

'LABEL_1'